/*
-- Query: SELECT * FROM geospots.GeoApp_geospots
LIMIT 0, 10000

-- Date: 2017-04-04 20:56
*/
INSERT INTO `GeoApp_geospots` (`id`,`name`,`description`,`latitude`,`longitude`,`added_by_id`,`location`,`voivodeship`) VALUES (1,'Odkrywkowa kopalnia kredy w Mielniku','Odkrywkowa kopalnia kredy jest jedyną tego typu kopalnią czynną obecnie w Polsce. Początki eksploatacji kredy w Mielniku datuje się na wiek XVI. Wydobywano ją początkowo do celów budowlanych metodą tzw. \"biedaszybów\". Aż do roku 1952 było to wydobycie ręczne wykorzystywane wyłącznie dla potrzeb okolicznych mieszkańców. Od połowy XX wieku rozpoczęto eksploatację na skalę przemysłową. Wybudowano również nowoczesny zakład przetwórczy. Dziś roczne wydobycie kredy wynosi około 80 tys. ton.',52.330204,23.051763,1,'Mielnik',10);
INSERT INTO `GeoApp_geospots` (`id`,`name`,`description`,`latitude`,`longitude`,`added_by_id`,`location`,`voivodeship`) VALUES (2,'Miedzianka','Miedzianka była swego czasu miejscem, w którym oprócz miedzi wydobywano również wapienie. O tym, że eksploatacja tego miejsca była znacząca, świadczą szyby i korytarze, które ciągną się we wnętrzu góry. Jeden z korytarzy ma być wkrótce otwarty dla zwiedzających.\r\n\r\n50.847348, 20.359168',50.847348,20.359168,1,'Miedzianka',13);
INSERT INTO `GeoApp_geospots` (`id`,`name`,`description`,`latitude`,`longitude`,`added_by_id`,`location`,`voivodeship`) VALUES (3,'Nasiłów','Kamieniołom w Nasiłowie położony na lewym brzegu Wisły w odległości ok. 7 km na południe od Puław, jest obok Bochotnicy znajdującej się po drugiej stronie rzeki.',51.344024,21.959523,1,'Nasiłów',13);
INSERT INTO `GeoApp_geospots` (`id`,`name`,`description`,`latitude`,`longitude`,`added_by_id`,`location`,`voivodeship`) VALUES (4,'Kamieniołom w Ostrówce','Karbon w Górach Świętokrzyskich jest niekompletny, brakuje bowiem górnokarbońskich utworów węglonośnych tak charakterystycznych dla tego systemu. W przeciwieństwie do skał dewońskich, utwory karbonu dolnego łatwo wietrzeją i są słabo odsłonięte.',50.842778,20.414167,1,'Ostrówka',13);
INSERT INTO `GeoApp_geospots` (`id`,`name`,`description`,`latitude`,`longitude`,`added_by_id`,`location`,`voivodeship`) VALUES (5,'Pod Capkami','Utwory eoceńskie rejestrują transgresję, która wkroczyła na obszar Tatr, sfałdowany (ruchy płaszczowinowe) i wypiętrzony po turonie w wyniku jednej z wcześniejszych faz orogenezy alpejskiej - fazy subhercyńskiej. Morze dotarło tutaj od strony znajdujących się na północy basenów Karpat zewnętrznych. Transgresywne utwory eocenu określane mianem \"eocenu numulitowego\" charakteryzują się dużą oboczną zmiennością zarówno pod względem wykształcenia jak i miąższości',49.279044,19.974818,1,'Zakopane',6);
