# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 20:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, upload_to='GeoApp/static/')),
            ],
        ),
        migrations.CreateModel(
            name='GeoSpots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=64)),
                ('voivodeship', models.IntegerField(choices=[(1, 'woj. dolnośląskie'), (2, 'woj. kujawsko-pomorskie'), (3, 'woj. lubelskie'), (4, 'woj. lubuskie'), (5, 'woj. łódzkie'), (6, 'woj. małopolskie'), (7, 'woj. mazowieckie'), (8, 'woj. opolskie'), (9, 'woj. podkarpackie'), (10, 'woj. podlaskie'), (11, 'woj. pomorskie'), (12, 'woj. śląskie'), (13, 'woj. świętokrzyskie'), (14, 'woj. warmińsko-mazurskie'), (15, 'woj. wielkopolskie'), (16, 'woj. zachodniopomorskie')])),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Geostanowisko',
                'verbose_name_plural': 'Geostanowiska',
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GeoApp.GeoSpots'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
