# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GeoApp.GeoSpots'),
        ),
    ]
